-- ============================================================================
-- DDL_GENERATION_QUEUE - Job queue for the unattended DDL worker.
--
-- A dedicated, auto-logon CONSOLE-session erwin+addin (DdlWorker user) polls
-- this table. For each PENDING row it opens MODEL_PATH at LEFT_VERSION via the
-- GUI Mart>Open automation, runs the proven cross-version Generate-DDL pipeline
-- against RIGHT_VERSION, writes the produced DDL back into RESULT_DDL, and marks
-- the row DONE (or FAILED + ERROR_MESSAGE).
--
-- Unlike DDL_APPROVAL_QUEUE (addin INSERTs only), this queue is read+written by
-- the addin worker: it CLAIMs (PENDING -> RUNNING) and finalizes (DONE/FAILED).
-- The producer (admin tool / operator) INSERTs PENDING rows.
--
-- STATUS lifecycle: PENDING -> RUNNING -> DONE | FAILED.
-- Single worker, sequential processing (erwin is single-instance-per-logon), so
-- contention is minimal; the CLAIM is still an atomic conditional UPDATE.
--
-- Three dialects below; each block is idempotent (re-runs are no-ops).
-- Run the block that matches your bootstrap DB.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- MSSQL
-- ----------------------------------------------------------------------------

IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name = 'DDL_GENERATION_QUEUE' AND type = 'U')
BEGIN
    CREATE TABLE [dbo].[DDL_GENERATION_QUEUE] (
        [ID]            INT IDENTITY(1,1) NOT NULL,
        [MODEL_PATH]    NVARCHAR(512)    NOT NULL,
        [LEFT_VERSION]  INT              NOT NULL,
        [RIGHT_VERSION] INT              NOT NULL,
        [STATUS]        NVARCHAR(32)     NOT NULL CONSTRAINT [DF_DDL_GEN_QUEUE_STATUS] DEFAULT ('PENDING'),
        [RESULT_DDL]    NVARCHAR(MAX)    NULL,
        [ERROR_MESSAGE] NVARCHAR(MAX)    NULL,
        [CREATED_AT]    DATETIME2(0)     NOT NULL CONSTRAINT [DF_DDL_GEN_QUEUE_CREATED] DEFAULT (SYSUTCDATETIME()),
        [STARTED_AT]    DATETIME2(0)     NULL,
        [FINISHED_AT]   DATETIME2(0)     NULL,
        [CLAIMED_BY]    NVARCHAR(128)    NULL,
        [RETRY_COUNT]   INT              NOT NULL CONSTRAINT [DF_DDL_GEN_QUEUE_RETRY] DEFAULT (0),
        CONSTRAINT [PK_DDL_GENERATION_QUEUE] PRIMARY KEY CLUSTERED ([ID] ASC)
    );

    CREATE INDEX [IX_DDL_GENERATION_QUEUE_STATUS]
        ON [dbo].[DDL_GENERATION_QUEUE] ([STATUS], [CREATED_AT] ASC);

    PRINT 'Created [dbo].[DDL_GENERATION_QUEUE]';
END
ELSE
    PRINT '[dbo].[DDL_GENERATION_QUEUE] already exists - skipped';
GO


-- ----------------------------------------------------------------------------
-- Oracle  (run separately, not in MSSQL batch)
-- ----------------------------------------------------------------------------
/*
DECLARE
    cnt INTEGER;
BEGIN
    SELECT COUNT(*) INTO cnt FROM user_tables WHERE table_name = 'DDL_GENERATION_QUEUE';
    IF cnt = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE DDL_GENERATION_QUEUE (
                ID            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                MODEL_PATH    VARCHAR2(512 CHAR) NOT NULL,
                LEFT_VERSION  NUMBER(10)         NOT NULL,
                RIGHT_VERSION NUMBER(10)         NOT NULL,
                STATUS        VARCHAR2(32 CHAR) DEFAULT 'PENDING' NOT NULL,
                RESULT_DDL    CLOB,
                ERROR_MESSAGE CLOB,
                CREATED_AT    TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
                STARTED_AT    TIMESTAMP,
                FINISHED_AT   TIMESTAMP,
                CLAIMED_BY    VARCHAR2(128 CHAR),
                RETRY_COUNT   NUMBER(10) DEFAULT 0 NOT NULL,
                CONSTRAINT PK_DDL_GENERATION_QUEUE PRIMARY KEY (ID)
            )
        ]';
        EXECUTE IMMEDIATE 'CREATE INDEX IX_DDL_GEN_QUEUE_STATUS ON DDL_GENERATION_QUEUE (STATUS, CREATED_AT)';
    END IF;
END;
/
*/


-- ----------------------------------------------------------------------------
-- PostgreSQL  (run separately, not in MSSQL batch)
-- ----------------------------------------------------------------------------
/*
CREATE TABLE IF NOT EXISTS "DDL_GENERATION_QUEUE" (
    "ID"            BIGSERIAL                       PRIMARY KEY,
    "MODEL_PATH"    VARCHAR(512)                    NOT NULL,
    "LEFT_VERSION"  INTEGER                         NOT NULL,
    "RIGHT_VERSION" INTEGER                         NOT NULL,
    "STATUS"        VARCHAR(32) DEFAULT 'PENDING'   NOT NULL,
    "RESULT_DDL"    TEXT,
    "ERROR_MESSAGE" TEXT,
    "CREATED_AT"    TIMESTAMP   DEFAULT (NOW() AT TIME ZONE 'utc') NOT NULL,
    "STARTED_AT"    TIMESTAMP,
    "FINISHED_AT"   TIMESTAMP,
    "CLAIMED_BY"    VARCHAR(128),
    "RETRY_COUNT"   INTEGER     DEFAULT 0 NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_DDL_GENERATION_QUEUE_STATUS"
    ON "DDL_GENERATION_QUEUE" ("STATUS", "CREATED_AT");
*/
