-- ============================================================================
-- DDL_APPROVAL_QUEUE - Persistence target for the addin's "Sent to Approve"
-- flow on the DDL Generation tab. Rows land here whenever a user runs
-- Generate DDL (or a DDL diff) in the addin and clicks "Sent to Approve" in
-- the review popup. The admin module is responsible for triage / review /
-- mark Approved or Rejected.
--
-- The addin INSERTs only. No UPDATE / DELETE / SELECT from the addin side.
-- All STATUS lifecycle is owned by the admin module.
--
-- Three dialects below; each block is idempotent (re-runs are no-ops).
-- Run the block that matches your bootstrap DB.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- MSSQL
-- ----------------------------------------------------------------------------

IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name = 'DDL_APPROVAL_QUEUE' AND type = 'U')
BEGIN
    CREATE TABLE [dbo].[DDL_APPROVAL_QUEUE] (
        [ID]            INT IDENTITY(1,1) NOT NULL,
        [CONFIG_ID]     INT              NOT NULL,
        [MODEL_NAME]    NVARCHAR(256)    NULL,
        [MODEL_LOCATOR] NVARCHAR(MAX)    NULL,
        [SOURCE_MODE]   NVARCHAR(64)     NOT NULL,
        [DBMS_TYPE]     NVARCHAR(64)     NULL,
        [DDL_TEXT]      NVARCHAR(MAX)    NOT NULL,
        [NOTE]          NVARCHAR(MAX)    NULL,
        [STATUS]        NVARCHAR(32)     NOT NULL CONSTRAINT [DF_DDL_APPROVAL_QUEUE_STATUS] DEFAULT ('Pending'),
        [SUBMITTED_BY]  NVARCHAR(128)    NULL,
        [SUBMITTED_AT]  DATETIME2(0)     NOT NULL CONSTRAINT [DF_DDL_APPROVAL_QUEUE_AT] DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT [PK_DDL_APPROVAL_QUEUE] PRIMARY KEY CLUSTERED ([ID] ASC)
    );

    CREATE INDEX [IX_DDL_APPROVAL_QUEUE_CONFIG_STATUS]
        ON [dbo].[DDL_APPROVAL_QUEUE] ([CONFIG_ID], [STATUS], [SUBMITTED_AT] DESC);

    PRINT 'Created [dbo].[DDL_APPROVAL_QUEUE]';
END
ELSE
    PRINT '[dbo].[DDL_APPROVAL_QUEUE] already exists - skipped';
GO


-- ----------------------------------------------------------------------------
-- Oracle  (run separately, not in MSSQL batch)
-- ----------------------------------------------------------------------------
/*
DECLARE
    cnt INTEGER;
BEGIN
    SELECT COUNT(*) INTO cnt FROM user_tables WHERE table_name = 'DDL_APPROVAL_QUEUE';
    IF cnt = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE DDL_APPROVAL_QUEUE (
                ID            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                CONFIG_ID     NUMBER(10)   NOT NULL,
                MODEL_NAME    VARCHAR2(256 CHAR),
                MODEL_LOCATOR CLOB,
                SOURCE_MODE   VARCHAR2(64 CHAR) NOT NULL,
                DBMS_TYPE     VARCHAR2(64 CHAR),
                DDL_TEXT      CLOB             NOT NULL,
                NOTE          CLOB,
                STATUS        VARCHAR2(32 CHAR) DEFAULT 'Pending' NOT NULL,
                SUBMITTED_BY  VARCHAR2(128 CHAR),
                SUBMITTED_AT  TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
                CONSTRAINT PK_DDL_APPROVAL_QUEUE PRIMARY KEY (ID)
            )
        ]';
        EXECUTE IMMEDIATE 'CREATE INDEX IX_DDL_APPR_CFG_STATUS ON DDL_APPROVAL_QUEUE (CONFIG_ID, STATUS, SUBMITTED_AT DESC)';
    END IF;
END;
/
*/


-- ----------------------------------------------------------------------------
-- PostgreSQL  (run separately, not in MSSQL batch)
-- ----------------------------------------------------------------------------
/*
CREATE TABLE IF NOT EXISTS "DDL_APPROVAL_QUEUE" (
    "ID"            BIGSERIAL                       PRIMARY KEY,
    "CONFIG_ID"     INTEGER                         NOT NULL,
    "MODEL_NAME"    VARCHAR(256),
    "MODEL_LOCATOR" TEXT,
    "SOURCE_MODE"   VARCHAR(64)                     NOT NULL,
    "DBMS_TYPE"     VARCHAR(64),
    "DDL_TEXT"      TEXT                            NOT NULL,
    "NOTE"          TEXT,
    "STATUS"        VARCHAR(32) DEFAULT 'Pending'   NOT NULL,
    "SUBMITTED_BY"  VARCHAR(128),
    "SUBMITTED_AT"  TIMESTAMP   DEFAULT (NOW() AT TIME ZONE 'utc') NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_DDL_APPROVAL_QUEUE_CONFIG_STATUS"
    ON "DDL_APPROVAL_QUEUE" ("CONFIG_ID", "STATUS", "SUBMITTED_AT" DESC);
*/
