-- ============================================================================
-- DB2 z/OS V12 & V13 - v1 -> v2 ALTER SCRIPT (REFERANS)
-- ============================================================================
-- ONEMLI NOT - ERWIN UYUM ETKISI:
-- v1/v2 SQL dosyalari Erwin DM uyumlu yazimda "isimsiz constraint"
-- kullaniyor. DB2 z/OS isimsiz constraint'lere otomatik isim atar.
-- DROP CONSTRAINT komutlarinda gercek isimleri SYSCAT.TABCONST'tan alin:
--   SELECT CONSTNAME FROM SYSIBM.SYSTABCONST
--   WHERE TBCREATOR='APP' AND TBNAME='ORDERS' AND TYPE='F';
-- ============================================================================

-- ============================================================================
-- 1. BAGIMLILIKLARI KOPAR
-- ============================================================================

DROP VIEW APP.VW_LEGACY_CUSTOMER;
DROP VIEW APP.VW_ORDER_DETAIL;
DROP VIEW APP.VW_CUSTOMER_SUMMARY;

-- TRG-02 (TR_ORDERS_TIMESTAMP) - manuel ekli ise drop
-- DROP TRIGGER APP.TR_ORDERS_TIMESTAMP;

-- FK'leri drop et (gercek isimler SYSIBM.SYSTABCONST'tan)
ALTER TABLE APP.ORDERS         DROP CONSTRAINT FK_ORDERS_PROMOTION;  -- FK-02
ALTER TABLE APP.ORDERS         DROP CONSTRAINT FK_ORDERS_CUSTOMER;   -- baseline rebuild
ALTER TABLE SALES.ORDER_ITEM   DROP CONSTRAINT FK_ORDER_ITEM_ORDERS; -- FK-03
ALTER TABLE SALES.ORDER_ITEM   DROP CONSTRAINT FK_ORDER_ITEM_PRODUCT;-- ORDER_ITEM tasinacak

-- Index'ler
DROP INDEX APP.IX_ORDERS_DATE;
DROP INDEX APP.IX_ORDERS_CUSTOMER;
DROP INDEX APP.IX_ORDERS_PROMOTION;
DROP INDEX APP.IX_TX_LOG;
DROP INDEX SALES.IX_OI_PROD;
DROP INDEX APP.IX_CUSTOMER_TAXNO;

-- UNIQUE constraint drop
ALTER TABLE APP.CUSTOMER DROP UNIQUE UQ_CUSTOMER_TAXNO;
DROP INDEX APP.UQI_CUSTOMER_TAXNO;

-- ============================================================================
-- 2. PRODUCT_ARCHIVE drop (TBL-02)
-- ============================================================================
DROP INDEX APP.IX_PRODUCT_ARCHIVE_PK;
DROP TABLE APP.PRODUCT_ARCHIVE;
DROP TABLESPACE APPDB.TS_PARC;

-- ============================================================================
-- 3. CUSTOMER_BACKUP -> CUSTOMER_HISTORY rename (TBL-03)
-- ============================================================================
RENAME TABLE APP.CUSTOMER_BACKUP TO CUSTOMER_HISTORY;
-- PK index'i yeniden olustur:
DROP INDEX APP.IX_CUSTOMER_BACKUP_PK;
CREATE UNIQUE INDEX APP.IX_CUSTOMER_HISTORY_PK
    ON APP.CUSTOMER_HISTORY (customer_id, snapshot_date)
    USING STOGROUP APPSG CLUSTER;

-- ============================================================================
-- 4. ORDER_ITEM SALES -> OPS schema move (TBL-04)
-- ============================================================================

CREATE TABLESPACE TS_OI IN APPDB
    USING STOGROUP APPSG BUFFERPOOL BP1 CCSID UNICODE;

CREATE TABLE OPS.ORDER_ITEM (
    order_id       INTEGER          NOT NULL,
    line_no        INTEGER          NOT NULL,
    product_id     INTEGER          NOT NULL,
    quantity       INTEGER          NOT NULL,
    unit_price     DECIMAL(12,2)    NOT NULL,
    discount_pct   DECIMAL(5,2),
    PRIMARY KEY (order_id, line_no)
)
IN APPDB.TS_OI;

CREATE UNIQUE INDEX OPS.IX_ORDER_ITEM_PK
    ON OPS.ORDER_ITEM (order_id, line_no)
    USING STOGROUP APPSG CLUSTER;

ALTER TABLE OPS.ORDER_ITEM ADD CHECK (quantity > 0);

-- Data migration (production'da)
-- INSERT INTO OPS.ORDER_ITEM (...) SELECT ... FROM SALES.ORDER_ITEM;

DROP INDEX SALES.IX_ORDER_ITEM_PK;
DROP TABLE SALES.ORDER_ITEM;
DROP TABLESPACE APPDB.TS_OIS;

-- COL-14 line_total generated column - manuel

-- ============================================================================
-- 5. TRANSACTION_LOG drop+create (PART-01, COL-13, PK-01, STO-02)
-- ============================================================================

DROP TABLE APP.TRANSACTION_LOG;
DROP TABLESPACE APPDB.TS_TXL;

CREATE TABLESPACE TS_TXL_PT IN APPDB
    USING STOGROUP APPSG BUFFERPOOL BP1 CCSID UNICODE
    NUMPARTS 4 COMPRESS YES;

CREATE TABLE APP.TRANSACTION_LOG (
    log_id         BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    txn_id         BIGINT           NOT NULL,
    customer_id    INTEGER,
    txn_date       TIMESTAMP        NOT NULL,
    txn_amount     DECIMAL(18,2)    NOT NULL,
    txn_type       VARCHAR(10)      NOT NULL,
    PRIMARY KEY (log_id)
)
IN APPDB.TS_TXL_PT;
-- PART-01 PARTITION BY RANGE (txn_date): manuel

CREATE INDEX APP.IX_TX_LOG_PART
    ON APP.TRANSACTION_LOG (txn_date)
    USING STOGROUP APPSG CLUSTER;

CREATE UNIQUE INDEX APP.IX_TX_LOG_PK
    ON APP.TRANSACTION_LOG (log_id)
    USING STOGROUP APPSG;

-- ============================================================================
-- 6. PROMOTION drop+create (PART-02 + composite PK)
-- ============================================================================

DROP INDEX APP.IX_PROMOTION_PK;
DROP TABLE APP.PROMOTION;
DROP TABLESPACE APPDB.TS_PROMO;

CREATE TABLESPACE TS_PROMO IN APPDB
    USING STOGROUP APPSG BUFFERPOOL BP1 CCSID UNICODE NUMPARTS 3;

CREATE TABLE APP.PROMOTION (
    promotion_id    INTEGER         NOT NULL,
    code            VARCHAR(30)     NOT NULL,
    description     VARCHAR(500),
    discount_pct    DECIMAL(5,2)    NOT NULL,
    start_date      DATE            NOT NULL,
    end_date        DATE            NOT NULL,
    PRIMARY KEY (promotion_id, start_date)
)
IN APPDB.TS_PROMO;
-- PART-02 PARTITION BY RANGE (start_date): manuel

ALTER TABLE APP.PROMOTION ADD CHECK (end_date >= start_date);

CREATE INDEX APP.IX_PROMOTION_PART
    ON APP.PROMOTION (start_date)
    USING STOGROUP APPSG CLUSTER;

CREATE UNIQUE INDEX APP.IX_PROMOTION_PK
    ON APP.PROMOTION (promotion_id, start_date)
    USING STOGROUP APPSG;

-- ============================================================================
-- 7. CUSTOMER kolon degisiklikleri
-- ============================================================================

-- COL-12 CCSID - manuel: ALTER TABLE APP.CUSTOMER ALTER COLUMN full_name
--                         SET DATA TYPE VARCHAR(150) CCSID UNICODE;

-- COL-05
ALTER TABLE APP.CUSTOMER ALTER COLUMN address SET DATA TYPE VARCHAR(250);

-- COL-03
ALTER TABLE APP.CUSTOMER RENAME COLUMN mobile_phone TO mobile_no;

-- COL-02
ALTER TABLE APP.CUSTOMER DROP COLUMN fax_number;

-- COL-09
ALTER TABLE APP.CUSTOMER ALTER COLUMN status SET WITH DEFAULT 'ACTIVE';

-- COL-01
ALTER TABLE APP.CUSTOMER ADD COLUMN email_verified SMALLINT NOT NULL WITH DEFAULT 0;

-- UQ-01
ALTER TABLE APP.CUSTOMER ADD UNIQUE (email);
CREATE UNIQUE INDEX APP.UQI_CUSTOMER_EMAIL
    ON APP.CUSTOMER (email) USING STOGROUP APPSG;

-- TBL-05 comment - manuel

-- ============================================================================
-- 8. ORDERS kolon degisiklikleri
-- ============================================================================

ALTER TABLE APP.ORDERS DROP CHECK CK_ORDERS_AMOUNT;

-- COL-04
ALTER TABLE APP.ORDERS ALTER COLUMN order_amount SET DATA TYPE BIGINT;

-- COL-07
ALTER TABLE APP.ORDERS ALTER COLUMN customer_id SET NOT NULL;

-- COL-10
ALTER TABLE APP.ORDERS ALTER COLUMN order_status SET WITH DEFAULT 'PENDING';

ALTER TABLE APP.ORDERS ADD CHECK (order_amount >= 0 AND order_amount <= 1000000);

-- COL-15 comment - manuel

-- ============================================================================
-- 9. CAMPAIGN: yeni tablo + tablespace (TBL-01)
-- ============================================================================

CREATE TABLESPACE TS_CAMP IN APPDB
    USING STOGROUP APPSG BUFFERPOOL BP1 CCSID UNICODE NUMPARTS 2;

CREATE TABLE APP.CAMPAIGN (
    campaign_id     INTEGER         NOT NULL,
    promotion_id    INTEGER         NOT NULL,
    promotion_start DATE            NOT NULL,
    campaign_name   VARCHAR(200)    NOT NULL,
    channel         VARCHAR(20)     NOT NULL,
    launch_date     DATE            NOT NULL,
    budget          DECIMAL(15,2)   NOT NULL,
    PRIMARY KEY (campaign_id, launch_date)
)
IN APPDB.TS_CAMP;

ALTER TABLE APP.CAMPAIGN ADD CHECK (budget >= 0);

ALTER TABLE APP.CAMPAIGN
    ADD FOREIGN KEY (promotion_id, promotion_start)
    REFERENCES APP.PROMOTION (promotion_id, start_date)
    ON DELETE CASCADE;

CREATE INDEX APP.IX_CAMPAIGN_PART
    ON APP.CAMPAIGN (launch_date)
    USING STOGROUP APPSG CLUSTER;

CREATE UNIQUE INDEX APP.IX_CAMPAIGN_PK
    ON APP.CAMPAIGN (campaign_id, launch_date)
    USING STOGROUP APPSG;

CREATE INDEX APP.IX_CAMPAIGN_PROMO
    ON APP.CAMPAIGN (promotion_id, promotion_start)
    USING STOGROUP APPSG;

-- ============================================================================
-- 10. FK'LERI YENIDEN KUR
-- ============================================================================

ALTER TABLE APP.ORDERS
    ADD FOREIGN KEY (customer_id) REFERENCES APP.CUSTOMER (customer_id)
    ON DELETE NO ACTION;

ALTER TABLE OPS.ORDER_ITEM
    ADD FOREIGN KEY (order_id) REFERENCES APP.ORDERS (order_id)
    ON DELETE CASCADE;

ALTER TABLE OPS.ORDER_ITEM
    ADD FOREIGN KEY (product_id) REFERENCES APP.PRODUCT (product_id)
    ON DELETE NO ACTION;

ALTER TABLE APP.TRANSACTION_LOG
    ADD FOREIGN KEY (customer_id) REFERENCES APP.CUSTOMER (customer_id)
    ON DELETE NO ACTION;

-- ============================================================================
-- 11. INDEX'LER (kalanlar)
-- ============================================================================

CREATE UNIQUE INDEX APP.IX_CUSTOMER_TAXNO
    ON APP.CUSTOMER (tax_no) USING STOGROUP APPSG;

CREATE INDEX APP.IX_CUSTOMER_EMAIL
    ON APP.CUSTOMER (email) USING STOGROUP APPSG;
-- IDX-09 INCLUDE (full_name) - manuel (UNIQUE flag + INCLUDE)

CREATE INDEX APP.IX_ORDERS_CUSTOMER
    ON APP.ORDERS (customer_id, order_date) USING STOGROUP APPSG;

CREATE INDEX APP.IX_ORDERS_DATE_DESC
    ON APP.ORDERS (order_date DESC) USING STOGROUP APPSG;

CREATE INDEX OPS.IX_ORDER_ITEM_PRODUCT
    ON OPS.ORDER_ITEM (product_id) USING STOGROUP APPSG;

CREATE INDEX APP.IX_TX_LOG
    ON APP.TRANSACTION_LOG (customer_id, txn_date) USING STOGROUP APPSG;

-- ============================================================================
-- 12. SEQUENCE'LER
-- ============================================================================

ALTER SEQUENCE APP.SEQ_ORDER_NUMBER RESTART INCREMENT BY 10;

CREATE SEQUENCE APP.SEQ_TRANSACTION_LOG
    AS BIGINT START WITH 1 INCREMENT BY 1 MINVALUE 1 CACHE 100 NO CYCLE;

-- ============================================================================
-- 13. TRIGGER'LAR - manuel
-- TRG-01 TR_CUSTOMER_AUDIT, TRG-02 TR_ORDERS_TIMESTAMP + TR_ORDERS_STATUS_LOG
-- (Erwin DB2 z/OS parser BEGIN ATOMIC, INSERT OR UPDATE, WHEN syntax'lari
-- sorunlu - Trigger Editor uzerinden manuel)
-- ============================================================================

-- ============================================================================
-- 14. VIEW'LER
-- ============================================================================

CREATE VIEW APP.VW_CUSTOMER_SUMMARY AS
SELECT c.customer_id, c.full_name, c.email, c.email_verified
FROM APP.CUSTOMER c;

CREATE VIEW APP.VW_ORDER_DETAIL AS
SELECT o.order_id, o.customer_id, o.order_date, o.order_amount, o.order_status
FROM APP.ORDERS o
WHERE o.order_status IN ('OPEN','PENDING');

CREATE VIEW APP.VW_TRANSACTION_DAILY AS
SELECT DATE(txn_date) AS txn_day, customer_id, txn_type,
       COUNT(*) AS txn_count, SUM(txn_amount) AS total_amount
FROM APP.TRANSACTION_LOG
GROUP BY DATE(txn_date), customer_id, txn_type;

-- ============================================================================
-- MANUEL ADIMLAR
-- ============================================================================
-- - COL-12: CCSID UNICODE
-- - COL-14 line_total: ALTER TABLE OPS.ORDER_ITEM ADD line_total DECIMAL(20,2)
--   GENERATED ALWAYS AS (quantity * unit_price);
-- - COL-15, TBL-05: COMMENT ON COLUMN/TABLE
-- - IDX-09 INCLUDE: UNIQUE flag + INCLUDE clause Index Editor'dan
-- - PART-01 TX_LOG: PARTITION BY RANGE (txn_date)
-- - PART-02 PROMOTION: PARTITION BY RANGE (start_date)
-- - TRG-01, TRG-02: Trigger Editor'dan body manuel

-- BITTI
