-- ============================================================================
-- Oracle 19c & 21c - v1 -> v2 ALTER SCRIPT (REFERANS)
-- ============================================================================
-- ONEMLI NOT - ERWIN UYUM ETKISI:
-- v1/v2 SQL dosyalari Erwin DM uyumlu yazimda "isimsiz constraint"
-- kullaniyor. Oracle bu constraint'lere otomatik isim atar (SYS_C00xxx).
-- Asagidaki DROP CONSTRAINT komutlarinda ELLE GERCEK ISIMLERI BULMAK GEREKIR:
--   - ALL_CONSTRAINTS view'dan owner+table_name+constraint_type ile bulun
--   - Ornegin: SELECT constraint_name FROM all_constraints
--     WHERE owner='APP' AND table_name='ORDERS' AND constraint_type='C'
--     AND search_condition LIKE '%order_amount%';
-- ============================================================================

-- ============================================================================
-- 1. BAGIMLILIKLARI KOPAR
-- ============================================================================

DROP VIEW APP.VW_LEGACY_CUSTOMER;
DROP VIEW APP.VW_ORDER_DETAIL;
DROP VIEW APP.VW_CUSTOMER_SUMMARY;

DROP TRIGGER APP.TR_ORDERS_TIMESTAMP;

-- FK'leri drop et (gercek isimleri ALL_CONSTRAINTS'tan bul)
ALTER TABLE APP.ORDERS         DROP CONSTRAINT FK_ORDERS_PROMOTION;  -- FK-02
ALTER TABLE APP.ORDERS         DROP CONSTRAINT FK_ORDERS_CUSTOMER;   -- baseline rebuild
ALTER TABLE SALES.ORDER_ITEM   DROP CONSTRAINT FK_ORDER_ITEM_ORDERS; -- FK-03
ALTER TABLE SALES.ORDER_ITEM   DROP CONSTRAINT FK_ORDER_ITEM_PRODUCT;-- ORDER_ITEM tasinacak

-- Index'ler
DROP INDEX APP.IX_ORDERS_DATE;        -- IDX-02
DROP INDEX APP.IX_ORDERS_CUSTOMER;    -- IDX-04
DROP INDEX APP.IX_ORDERS_PROMOTION;   -- FK-02 sonrasi
DROP INDEX APP.IX_TX_LOG;
DROP INDEX SALES.IX_OI_PROD;          -- IDX-03 rename
DROP INDEX APP.IX_CUSTOMER_TAXNO;     -- IDX-06 UNIQUE icin

-- UNIQUE constraint drop (UQ-02 - gercek isim ALL_CONSTRAINTS'tan)
ALTER TABLE APP.CUSTOMER DROP CONSTRAINT UQ_CUSTOMER_TAXNO;

-- ============================================================================
-- 2. SEQUENCE'LER
-- ============================================================================

-- SEQ-02: INCREMENT 1 -> 10
ALTER SEQUENCE APP.SEQ_ORDER_NUMBER INCREMENT BY 10;

-- SEQ-01: yeni
CREATE SEQUENCE APP.SEQ_TRANSACTION_LOG
    START WITH 1 INCREMENT BY 1 MINVALUE 1 CACHE 100 NOCYCLE;

-- ============================================================================
-- 3. TRANSACTION_LOG: drop+create
-- ============================================================================

DROP TABLE APP.TRANSACTION_LOG;

CREATE TABLE APP.TRANSACTION_LOG (
    log_id         NUMBER(19)       GENERATED BY DEFAULT AS IDENTITY,
    txn_id         NUMBER(19)       NOT NULL,
    customer_id    NUMBER(10),
    txn_date       TIMESTAMP        NOT NULL,
    txn_amount     NUMBER(18,2)     NOT NULL,
    txn_type       VARCHAR2(10)     NOT NULL,
    PRIMARY KEY (log_id)
);
-- PART-01, STO-02: manuel (PARTITION BY RANGE, COMPRESS BASIC)

-- ============================================================================
-- 4. PROMOTION: drop+create (PART-02, PART-04, composite PK + UNIQUE)
-- ============================================================================

DROP TABLE APP.PROMOTION CASCADE CONSTRAINTS;

CREATE TABLE APP.PROMOTION (
    promotion_id    NUMBER(10)      NOT NULL,
    code            VARCHAR2(30)    NOT NULL,
    description     VARCHAR2(500),
    discount_pct    NUMBER(5,2)     NOT NULL,
    region          VARCHAR2(10)    NOT NULL,
    start_date      DATE            NOT NULL,
    end_date        DATE            NOT NULL,
    PRIMARY KEY (promotion_id, start_date, region)
);

ALTER TABLE APP.PROMOTION ADD UNIQUE (promotion_id);
ALTER TABLE APP.PROMOTION ADD CHECK (end_date >= start_date);
-- PART-02, PART-04: manuel (PARTITION BY RANGE + SUBPARTITION BY LIST)

-- ============================================================================
-- 5. PRODUCT_ARCHIVE drop (TBL-02)
-- ============================================================================
DROP TABLE APP.PRODUCT_ARCHIVE CASCADE CONSTRAINTS;

-- ============================================================================
-- 6. CUSTOMER_BACKUP -> CUSTOMER_HISTORY rename (TBL-03)
-- ============================================================================
ALTER TABLE APP.CUSTOMER_BACKUP RENAME TO CUSTOMER_HISTORY;

-- ============================================================================
-- 7. ORDER_ITEM: SALES -> OPS schema move (TBL-04)
-- Oracle'da cross-schema RENAME yok, CTAS pattern.
-- v2 farklarini ayni anda uyguluyoruz.
-- ============================================================================

CREATE TABLE OPS.ORDER_ITEM (
    order_id       NUMBER(10)       NOT NULL,
    line_no        NUMBER(10)       NOT NULL,
    product_id     NUMBER(10)       NOT NULL,
    quantity       NUMBER(10)       NOT NULL,
    unit_price     NUMBER(12,2)     NOT NULL,
    discount_pct   NUMBER(5,2),
    PRIMARY KEY (order_id, line_no)
)
TABLESPACE TS_DATA;

-- Data migration (production'da gerekli)
-- INSERT INTO OPS.ORDER_ITEM (...) SELECT ... FROM SALES.ORDER_ITEM;

DROP TABLE SALES.ORDER_ITEM CASCADE CONSTRAINTS;

ALTER TABLE OPS.ORDER_ITEM ADD CHECK (quantity > 0);
-- COL-14 line_total VIRTUAL: manuel

-- ============================================================================
-- 8. CUSTOMER kolon degisiklikleri
-- ============================================================================

-- COL-12: VARCHAR2 -> NVARCHAR2 (temp kolon pattern)
ALTER TABLE APP.CUSTOMER ADD full_name_new NVARCHAR2(150);
UPDATE APP.CUSTOMER SET full_name_new = full_name;
ALTER TABLE APP.CUSTOMER MODIFY full_name_new NVARCHAR2(150) NOT NULL;
ALTER TABLE APP.CUSTOMER DROP COLUMN full_name;
ALTER TABLE APP.CUSTOMER RENAME COLUMN full_name_new TO full_name;

-- COL-05
ALTER TABLE APP.CUSTOMER MODIFY address VARCHAR2(250);

-- COL-03
ALTER TABLE APP.CUSTOMER RENAME COLUMN mobile_phone TO mobile_no;

-- COL-02
ALTER TABLE APP.CUSTOMER DROP COLUMN fax_number;

-- COL-09
ALTER TABLE APP.CUSTOMER MODIFY status DEFAULT 'ACTIVE';

-- COL-01
ALTER TABLE APP.CUSTOMER ADD email_verified NUMBER(1) DEFAULT 0 NOT NULL;

-- UQ-01
ALTER TABLE APP.CUSTOMER ADD UNIQUE (email);

-- TBL-05 comment - manuel: COMMENT ON TABLE APP.CUSTOMER IS '...'

-- ============================================================================
-- 9. ORDERS kolon degisiklikleri
-- ============================================================================

-- CHK-02 eski drop (gercek isim ALL_CONSTRAINTS'tan)
ALTER TABLE APP.ORDERS DROP CONSTRAINT CK_ORDERS_AMOUNT;

-- COL-04
ALTER TABLE APP.ORDERS MODIFY order_amount NUMBER(19);

-- COL-07
ALTER TABLE APP.ORDERS MODIFY customer_id NOT NULL;

-- COL-10
ALTER TABLE APP.ORDERS MODIFY order_status DEFAULT 'PENDING';

-- CHK-02 yeni
ALTER TABLE APP.ORDERS ADD CHECK (order_amount >= 0 AND order_amount <= 1000000);

-- COL-15 comment - manuel

-- ============================================================================
-- 10. CAMPAIGN: yeni tablo (TBL-01)
-- ============================================================================

CREATE TABLE APP.CAMPAIGN (
    campaign_id     NUMBER(10)      NOT NULL,
    promotion_id    NUMBER(10)      NOT NULL,
    campaign_name   VARCHAR2(200)   NOT NULL,
    channel         VARCHAR2(20)    NOT NULL,
    launch_date     DATE            NOT NULL,
    budget          NUMBER(15,2)    NOT NULL,
    PRIMARY KEY (campaign_id)
);

ALTER TABLE APP.CAMPAIGN ADD CHECK (budget >= 0);

ALTER TABLE APP.CAMPAIGN
    ADD FOREIGN KEY (promotion_id) REFERENCES APP.PROMOTION (promotion_id)
    ON DELETE CASCADE;

CREATE INDEX APP.IX_CAMPAIGN_PROMO ON APP.CAMPAIGN (promotion_id);

-- ============================================================================
-- 11. FK'LERI YENIDEN KUR
-- ============================================================================

ALTER TABLE APP.ORDERS
    ADD FOREIGN KEY (customer_id) REFERENCES APP.CUSTOMER (customer_id);

ALTER TABLE OPS.ORDER_ITEM
    ADD FOREIGN KEY (order_id) REFERENCES APP.ORDERS (order_id)
    ON DELETE CASCADE;

ALTER TABLE OPS.ORDER_ITEM
    ADD FOREIGN KEY (product_id) REFERENCES APP.PRODUCT (product_id);

ALTER TABLE APP.TRANSACTION_LOG
    ADD FOREIGN KEY (customer_id) REFERENCES APP.CUSTOMER (customer_id);

-- ============================================================================
-- 12. INDEX'LER
-- ============================================================================

CREATE UNIQUE INDEX APP.IX_CUSTOMER_TAXNO ON APP.CUSTOMER (tax_no);
CREATE INDEX APP.IX_CUSTOMER_EMAIL ON APP.CUSTOMER (email);
-- IDX-08: CREATE INDEX APP.IX_CUSTOMER_EMAIL_UPPER ON APP.CUSTOMER (UPPER(email)); -- manuel

CREATE INDEX APP.IX_ORDERS_CUSTOMER ON APP.ORDERS (customer_id, order_date);
CREATE INDEX APP.IX_ORDERS_DATE_DESC ON APP.ORDERS (order_date DESC);
CREATE INDEX OPS.IX_ORDER_ITEM_PRODUCT ON OPS.ORDER_ITEM (product_id);
CREATE INDEX APP.IX_TX_LOG ON APP.TRANSACTION_LOG (customer_id, txn_date);

-- ============================================================================
-- 13. TRIGGER'LAR
-- ============================================================================

CREATE OR REPLACE TRIGGER APP.TR_ORDERS_TIMESTAMP
BEFORE INSERT OR UPDATE ON APP.ORDERS
FOR EACH ROW
BEGIN
    :NEW.last_updated := SYSTIMESTAMP;

    IF UPDATING('order_status') AND :OLD.order_status != :NEW.order_status THEN
        INSERT INTO APP.TRANSACTION_LOG
            (txn_id, customer_id, txn_date, txn_amount, txn_type)
        VALUES
            (APP.SEQ_TRANSACTION_LOG.NEXTVAL, :NEW.customer_id,
             SYSTIMESTAMP, :NEW.order_amount, 'STATUS_CHG');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER APP.TR_CUSTOMER_AUDIT
AFTER UPDATE OF email, status ON APP.CUSTOMER
FOR EACH ROW
BEGIN
    NULL;
END;
/

-- ============================================================================
-- 14. VIEW'LER + MV
-- ============================================================================

CREATE OR REPLACE VIEW APP.VW_CUSTOMER_SUMMARY AS
SELECT c.customer_id, c.full_name, c.email, c.email_verified
FROM APP.CUSTOMER c;

CREATE OR REPLACE VIEW APP.VW_ORDER_DETAIL AS
SELECT o.order_id, o.customer_id, o.order_date, o.order_amount, o.order_status
FROM APP.ORDERS o
WHERE o.order_status IN ('OPEN','PENDING');

-- VW-05 materialized view - manuel:
-- CREATE MATERIALIZED VIEW APP.MV_ORDER_DETAIL
-- BUILD IMMEDIATE REFRESH COMPLETE ON DEMAND
-- AS SELECT ... FROM APP.ORDERS WHERE ...;

CREATE OR REPLACE VIEW APP.VW_TRANSACTION_DAILY AS
SELECT TRUNC(txn_date) AS txn_day, customer_id, txn_type,
       COUNT(*) AS txn_count, SUM(txn_amount) AS total_amount
FROM APP.TRANSACTION_LOG
GROUP BY TRUNC(txn_date), customer_id, txn_type;

-- ============================================================================
-- MANUEL ADIMLAR
-- ============================================================================
-- - COL-14 (line_total VIRTUAL): ALTER TABLE OPS.ORDER_ITEM ADD line_total
--   NUMBER(20,2) GENERATED ALWAYS AS (quantity * unit_price) VIRTUAL;
-- - COL-15, TBL-05: COMMENT ON COLUMN/TABLE
-- - IDX-08: CREATE INDEX ... ON APP.CUSTOMER (UPPER(email))
-- - PART-01: TRANSACTION_LOG PARTITION BY RANGE (txn_date)
-- - PART-02, PART-04: PROMOTION PARTITION BY RANGE + SUBPARTITION BY LIST
-- - STO-02: COMPRESS BASIC
-- - VW-05: CREATE MATERIALIZED VIEW

-- BITTI
