using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Windows.Forms;

namespace ErwinAddIn
{
    /// <summary>
    /// DDL Script Generator for erwin Data Modeler
    /// Converted from PowerDesigner GenerateDDL/GenerateScript functions
    /// </summary>
    public class DDLGenerator
    {
        private dynamic _scapi;
        private dynamic _model;
        private dynamic _session;

        public string CurrentSchema { get; set; }
        public string DatabaseName { get; set; }
        public string Environment { get; set; }
        public string OutputPath { get; set; }
        public string UserName { get; set; }

        #region Generation Options (from DefaultGenOptions)

        public bool GenerateCreateTable { get; set; } = true;
        public bool GenerateDropTable { get; set; } = false;
        public bool GenerateTableComment { get; set; } = true;
        public bool GenerateColumnComment { get; set; } = true;
        public bool GenerateCreatePrimaryKey { get; set; } = true;
        public bool GenerateDropPrimaryKey { get; set; } = false;
        public bool GenerateCreateIndex { get; set; } = true;
        public bool GenerateDropIndex { get; set; } = false;
        public bool GenerateCreateView { get; set; } = true;
        public bool GenerateDropView { get; set; } = false;
        public bool GenerateCreateProcedure { get; set; } = true;
        public bool GenerateDropProcedure { get; set; } = false;
        public bool GenerateAlterScript { get; set; } = false;
        public bool UseOwnerPrefix { get; set; } = true;

        #endregion

        public DDLGenerator(dynamic scapi)
        {
            _scapi = scapi;
            OutputPath = System.IO.Path.GetTempPath();
            UserName = System.Environment.UserName;
        }

        /// <summary>
        /// Opens a model for DDL generation
        /// </summary>
        public bool OpenModel(dynamic model)
        {
            try
            {
                _model = model;
                _session = _scapi.Sessions.Add();
                _session.Open(_model);
                return true;
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Model açma hatası: {ex.Message}", "Hata",
                    MessageBoxButtons.OK, MessageBoxIcon.Error);
                return false;
            }
        }

        /// <summary>
        /// Generates DDL script for selected objects or entire model
        /// </summary>
        public string GenerateDDL(List<string> selectedEntities = null)
        {
            var sb = new StringBuilder();

            try
            {
                // Add header
                sb.AppendLine("-- ============================================");
                sb.AppendLine($"-- DDL Script Generated by erwin AddIn");
                sb.AppendLine($"-- Generated by: {UserName}");
                sb.AppendLine($"-- Generated on: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
                sb.AppendLine($"-- Schema: {CurrentSchema}");
                sb.AppendLine($"-- Database: {DatabaseName}");
                sb.AppendLine($"-- Environment: {Environment}");
                sb.AppendLine("-- ============================================");
                sb.AppendLine();

                // Get entities
                dynamic modelObjects = _session.ModelObjects;
                dynamic entities = modelObjects.Collect("Entity");

                for (int i = 0; i < entities.Count; i++)
                {
                    dynamic entity = entities.Item(i);
                    string entityName = GetPropertyValue(entity, "Name");
                    string physicalName = GetPropertyValue(entity, "Physical_Name") ?? entityName;

                    // Filter by selection if provided
                    if (selectedEntities != null && !selectedEntities.Contains(entityName))
                        continue;

                    // Generate DROP TABLE if enabled
                    if (GenerateDropTable)
                    {
                        sb.AppendLine($"-- Drop Table: {physicalName}");
                        sb.AppendLine($"DROP TABLE {GetFullTableName(physicalName)};");
                        sb.AppendLine();
                    }

                    // Generate CREATE TABLE
                    if (GenerateCreateTable)
                    {
                        sb.AppendLine($"-- Create Table: {physicalName}");
                        sb.AppendLine($"CREATE TABLE {GetFullTableName(physicalName)}");
                        sb.AppendLine("(");

                        // Get attributes/columns
                        dynamic attributes = modelObjects.Collect(entity).Collect("Attribute");
                        var columns = new List<string>();

                        for (int j = 0; j < attributes.Count; j++)
                        {
                            dynamic attr = attributes.Item(j);
                            string colName = GetPropertyValue(attr, "Physical_Name") ?? GetPropertyValue(attr, "Name");
                            string dataType = GetPropertyValue(attr, "Datatype") ?? "VARCHAR2(255)";
                            string nullable = GetPropertyValue(attr, "Null_Option") == "NOT NULL" ? " NOT NULL" : "";

                            columns.Add($"    {colName} {dataType}{nullable}");
                        }

                        sb.AppendLine(string.Join(",\n", columns));
                        sb.AppendLine(");");
                        sb.AppendLine();

                        // Generate table comment
                        if (GenerateTableComment)
                        {
                            string comment = GetPropertyValue(entity, "Definition") ?? GetPropertyValue(entity, "Note");
                            if (!string.IsNullOrEmpty(comment))
                            {
                                sb.AppendLine($"COMMENT ON TABLE {GetFullTableName(physicalName)} IS '{EscapeString(comment)}';");
                                sb.AppendLine();
                            }
                        }
                    }

                    // Generate PRIMARY KEY
                    if (GenerateCreatePrimaryKey)
                    {
                        // Try to find key groups
                        string pkColumns = GetPrimaryKeyColumns(entity);
                        if (!string.IsNullOrEmpty(pkColumns))
                        {
                            sb.AppendLine($"ALTER TABLE {GetFullTableName(physicalName)}");
                            sb.AppendLine($"ADD CONSTRAINT PK_{physicalName} PRIMARY KEY ({pkColumns});");
                            sb.AppendLine();
                        }
                    }

                    // Generate INDEX
                    if (GenerateCreateIndex)
                    {
                        sb.AppendLine($"-- Indexes for: {physicalName}");
                        // Index generation would go here based on model metadata
                        sb.AppendLine();
                    }
                }

                // Generate VIEWS if enabled
                if (GenerateCreateView)
                {
                    sb.AppendLine("-- ============================================");
                    sb.AppendLine("-- VIEWS");
                    sb.AppendLine("-- ============================================");
                    // View generation would go here
                    sb.AppendLine();
                }

                // Generate PROCEDURES if enabled
                if (GenerateCreateProcedure)
                {
                    sb.AppendLine("-- ============================================");
                    sb.AppendLine("-- PROCEDURES");
                    sb.AppendLine("-- ============================================");
                    // Procedure generation would go here
                    sb.AppendLine();
                }

                sb.AppendLine("-- ============================================");
                sb.AppendLine("-- End of DDL Script");
                sb.AppendLine("-- ============================================");
            }
            catch (Exception ex)
            {
                sb.AppendLine($"-- ERROR: {ex.Message}");
            }

            return sb.ToString();
        }

        /// <summary>
        /// Saves DDL script to file
        /// </summary>
        public string SaveScript(string ddlContent, string customFileName = null)
        {
            string fileName = customFileName ?? ErwinUtilities.GenerateScriptFileName(CurrentSchema);
            string fullPath = Path.Combine(OutputPath, fileName);

            try
            {
                File.WriteAllText(fullPath, ddlContent, Encoding.UTF8);
                return fullPath;
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Script kaydetme hatası: {ex.Message}", "Hata",
                    MessageBoxButtons.OK, MessageBoxIcon.Error);
                return null;
            }
        }

        /// <summary>
        /// Shows DDL preview dialog
        /// </summary>
        public DialogResult ShowPreview(string ddlContent)
        {
            using (var form = new Form())
            {
                form.Text = "DDL Script Preview";
                form.Size = new System.Drawing.Size(800, 600);
                form.StartPosition = FormStartPosition.CenterScreen;

                var textBox = new TextBox
                {
                    Multiline = true,
                    ScrollBars = ScrollBars.Both,
                    Dock = DockStyle.Fill,
                    Font = new System.Drawing.Font("Consolas", 10),
                    Text = ddlContent,
                    ReadOnly = true
                };

                var btnSave = new Button
                {
                    Text = "Kaydet",
                    Dock = DockStyle.Bottom,
                    Height = 35,
                    DialogResult = DialogResult.OK
                };

                var btnCancel = new Button
                {
                    Text = "İptal",
                    Dock = DockStyle.Bottom,
                    Height = 35,
                    DialogResult = DialogResult.Cancel
                };

                form.Controls.Add(textBox);
                form.Controls.Add(btnSave);
                form.Controls.Add(btnCancel);

                return form.ShowDialog();
            }
        }

        /// <summary>
        /// Closes the session
        /// </summary>
        public void Close()
        {
            try
            {
                _session?.Close();
                _scapi?.Sessions?.Clear();
            }
            catch { }
        }

        #region Helper Methods

        private string GetPropertyValue(dynamic obj, string propertyName)
        {
            try
            {
                return obj.Properties(propertyName).Value?.ToString();
            }
            catch
            {
                try
                {
                    // Try direct property access
                    var prop = obj.GetType().GetProperty(propertyName);
                    return prop?.GetValue(obj)?.ToString();
                }
                catch
                {
                    return null;
                }
            }
        }

        private string GetFullTableName(string tableName)
        {
            if (UseOwnerPrefix && !string.IsNullOrEmpty(CurrentSchema))
            {
                return $"{CurrentSchema}.{tableName}";
            }
            return tableName;
        }

        private string GetPrimaryKeyColumns(dynamic entity)
        {
            // This would need to be implemented based on erwin's key group structure
            // Placeholder implementation
            try
            {
                dynamic modelObjects = _session.ModelObjects;
                dynamic keyGroups = modelObjects.Collect(entity).Collect("Key_Group");

                for (int i = 0; i < keyGroups.Count; i++)
                {
                    dynamic keyGroup = keyGroups.Item(i);
                    string keyType = GetPropertyValue(keyGroup, "Key_Group_Type");

                    if (keyType == "PK" || keyType == "Primary")
                    {
                        // Get key columns
                        // This would need more implementation
                        return GetPropertyValue(keyGroup, "Key_Group_Member_Column");
                    }
                }
            }
            catch { }

            return null;
        }

        private string EscapeString(string input)
        {
            return input?.Replace("'", "''") ?? "";
        }

        #endregion
    }
}
