# Post-build comhost.dll fix wrapper. Invokes tools/comhost-embed which
# properly embeds the .clsidmap resource into the project's comhost.dll
# (the .NET 10 SDK target _CreateComHost runs but silently fails to do
# this, verified 2026-05-26 against SDK 10.0.102; without this fix
# CoCreateInstance returns TYPE_E_CANTLOADLIBRARY and erwin's Add-In
# Manager hides the menu entry on validation).
#
# Idempotent: if the SDK ever starts producing a working comhost.dll
# again, this just re-does what it already did and produces identical
# bytes. Safe to run on every build.
#
# Usage:
#   pwsh scripts\embed-comhost.ps1               -> default Debug
#   pwsh scripts\embed-comhost.ps1 -Configuration Release
param(
    [string]$Configuration = 'Debug',
    [string]$RepoRoot      = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path,
    # Optional explicit comhost target list. When omitted, defaults to
    # bin\<Configuration>\net10.0-windows\... + the publish subdir. Used
    # by package.ps1 to embed into a custom output dir without having to
    # hardcode bin path conventions.
    [string[]]$ComHostPath = @()
)

$ErrorActionPreference = 'Stop'

# 1. Locate the SDK template comhost.dll (ships under the app host pack)
$sdkHostPacks = 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x64'
if (-not (Test-Path $sdkHostPacks)) {
    Write-Host "ERROR: SDK app-host pack root not found at $sdkHostPacks" -ForegroundColor Red
    exit 1
}
# Pick the highest installed version - we target net10.0 in the addin
# csproj so 10.x packs are required to be present. If multiple are
# installed, latest wins.
$templateRoot = Get-ChildItem $sdkHostPacks -Directory |
                Where-Object { $_.Name -match '^10\.' } |
                Sort-Object { [Version]$_.Name } -Descending |
                Select-Object -First 1
if (-not $templateRoot) {
    Write-Host "ERROR: no 10.x app-host pack found under $sdkHostPacks" -ForegroundColor Red
    exit 2
}
$template = Join-Path $templateRoot.FullName 'runtimes\win-x64\native\comhost.dll'
if (-not (Test-Path $template)) {
    Write-Host "ERROR: template comhost.dll not found at $template" -ForegroundColor Red
    exit 3
}

# 2. Build the embed helper (cached after first build)
$helperProj = Join-Path $RepoRoot 'tools\comhost-embed\comhost-embed.csproj'
$helperBin  = Join-Path $RepoRoot 'tools\comhost-embed\bin\Release\net10.0\comhost-embed.exe'
if (-not (Test-Path $helperBin)) {
    Write-Host "Building tools/comhost-embed (first run)..." -ForegroundColor Gray
    & dotnet build $helperProj -c Release --nologo --verbosity quiet
    if ($LASTEXITCODE -ne 0) { Write-Host "comhost-embed build FAILED" -ForegroundColor Red; exit 4 }
}

# 3. Find the addin's clsidmap (generated by the SDK target into obj/)
$clsidMap = Join-Path $RepoRoot "obj\$Configuration\net10.0-windows\EliteSoft.Erwin.AddIn.clsidmap"
if (-not (Test-Path $clsidMap)) {
    Write-Host "ERROR: .clsidmap not found at $clsidMap (run dotnet build first)" -ForegroundColor Red
    exit 5
}

# 4. Target the addin's comhost.dll in the build output. Caller can
# override via -ComHostPath for custom output dirs (e.g. package.ps1
# publishes to a release staging dir, not bin/).
if ($ComHostPath.Count -eq 0) {
    $ComHostPath = @(
        (Join-Path $RepoRoot "bin\$Configuration\net10.0-windows\EliteSoft.Erwin.AddIn.comhost.dll"),
        (Join-Path $RepoRoot "bin\$Configuration\net10.0-windows\publish\EliteSoft.Erwin.AddIn.comhost.dll")
    )
}

Write-Host "Embedding clsidmap into comhost.dll (SDK CreateComHostTask workaround)..." -ForegroundColor Cyan
foreach ($t in $ComHostPath | Where-Object { Test-Path (Split-Path $_) }) {
    & $helperBin $template $t $clsidMap
    if ($LASTEXITCODE -ne 0) {
        Write-Host "comhost-embed FAILED for $t" -ForegroundColor Red
        exit 6
    }
    Write-Host "  embedded into $t" -ForegroundColor Green
}
