using EliteSoft.Erwin.AlterDdl.Core.Emitting;
using EliteSoft.Erwin.AlterDdl.Core.Emitting.Dialect;
using EliteSoft.Erwin.AlterDdl.Core.Models;

using FluentAssertions;

using Xunit;

namespace EliteSoft.Erwin.AlterDdl.Core.Tests;

public class AttributePropertyChangeTests
{
    private static readonly ObjectRef Customer = new("{E1}+0", "CUSTOMER", "Entity");
    private static readonly ObjectRef OrderCol = new("{A1}+0", "customer_id", "Attribute");
    private static readonly ObjectRef StatusCol = new("{A2}+0", "status", "Attribute");
    private static readonly ObjectRef LogIdCol = new("{A3}+0", "log_id", "Attribute");

    private static readonly ModelMetadata MssqlMeta = new("{PU}+0", "t", "Physical", "SQL Server", 15, 0);
    private static readonly ModelMetadata OracleMeta = new("{PU}+0", "t", "Physical", "Oracle", 19, 0);
    private static readonly ModelMetadata Db2Meta = new("{PU}+0", "t", "Physical", "Db2", 12, 0);

    private static CompareResult Result(ModelMetadata meta, params Change[] changes) =>
        new(meta, meta, changes, new CompareArtifact("x.xls", 0, 0));

    // ---------- MSSQL ----------

    [Fact]
    public void Mssql_NullabilityChanged_emits_full_ALTER_COLUMN_with_datatype_lookup()
    {
        var tmp = Path.GetTempFileName();
        try
        {
            File.WriteAllText(tmp, "CREATE TABLE [app].[CUSTOMER] ([customer_id] INT NOT NULL);");
            var r = Result(MssqlMeta, new AttributeNullabilityChanged(OrderCol, Customer, true, false))
                with { RightDdl = new DdlArtifact(tmp, new FileInfo(tmp).Length, "SQL Server") };
            new MssqlEmitter().Emit(r).Statements[0].Sql
                .Should().Be("ALTER TABLE [CUSTOMER] ALTER COLUMN [customer_id] INT NOT NULL;");
        }
        finally { try { File.Delete(tmp); } catch { } }
    }

    [Fact]
    public void Mssql_DefaultChanged_add_emits_add_default_with_drop_todo()
    {
        var r = Result(MssqlMeta, new AttributeDefaultChanged(StatusCol, Customer, "", "'ACTIVE'"));
        var sql = new MssqlEmitter().Emit(r).Statements[0].Sql;
        sql.Should().Contain("ALTER TABLE [CUSTOMER] ADD DEFAULT ('ACTIVE') FOR [status]");
        sql.Should().Contain("-- TODO: DROP existing DEFAULT constraint");
    }

    [Fact]
    public void Mssql_IdentityChanged_emits_rebuild_todo()
    {
        var r = Result(MssqlMeta, new AttributeIdentityChanged(LogIdCol, Customer, false, true));
        var sql = new MssqlEmitter().Emit(r).Statements[0].Sql;
        sql.Should().Contain("TODO").And.Contain("IDENTITY");
    }

    // ---------- Oracle ----------

    [Fact]
    public void Oracle_NullabilityChanged_uses_MODIFY_NOT_NULL()
    {
        var r = Result(OracleMeta, new AttributeNullabilityChanged(OrderCol, Customer, true, false));
        new OracleEmitter().Emit(r).Statements[0].Sql
            .Should().Be("ALTER TABLE \"CUSTOMER\" MODIFY (\"customer_id\" NOT NULL);");
    }

    [Fact]
    public void Oracle_DefaultChanged_uses_MODIFY_DEFAULT()
    {
        var r = Result(OracleMeta, new AttributeDefaultChanged(StatusCol, Customer, "", "'ACTIVE'"));
        new OracleEmitter().Emit(r).Statements[0].Sql
            .Should().Be("ALTER TABLE \"CUSTOMER\" MODIFY (\"status\" DEFAULT 'ACTIVE');");
    }

    [Fact]
    public void Oracle_IdentityChanged_add_uses_GENERATED_BY_DEFAULT()
    {
        var r = Result(OracleMeta, new AttributeIdentityChanged(LogIdCol, Customer, false, true));
        new OracleEmitter().Emit(r).Statements[0].Sql
            .Should().Be("ALTER TABLE \"CUSTOMER\" MODIFY (\"log_id\" GENERATED BY DEFAULT AS IDENTITY);");
    }

    // ---------- Db2 ----------

    [Fact]
    public void Db2_NullabilityChanged_uses_SET_NOT_NULL_or_DROP_NOT_NULL()
    {
        var r = Result(Db2Meta, new AttributeNullabilityChanged(OrderCol, Customer, true, false));
        new Db2Emitter().Emit(r).Statements[0].Sql
            .Should().Be("ALTER TABLE \"CUSTOMER\" ALTER COLUMN \"customer_id\" SET NOT NULL;");

        var r2 = Result(Db2Meta, new AttributeNullabilityChanged(OrderCol, Customer, false, true));
        new Db2Emitter().Emit(r2).Statements[0].Sql
            .Should().Be("ALTER TABLE \"CUSTOMER\" ALTER COLUMN \"customer_id\" DROP NOT NULL;");
    }

    [Fact]
    public void Db2_DefaultChanged_add_uses_SET_DEFAULT()
    {
        var r = Result(Db2Meta, new AttributeDefaultChanged(StatusCol, Customer, "", "'ACTIVE'"));
        new Db2Emitter().Emit(r).Statements[0].Sql
            .Should().Be("ALTER TABLE \"CUSTOMER\" ALTER COLUMN \"status\" SET DEFAULT 'ACTIVE';");
    }

    [Fact]
    public void Db2_DefaultChanged_drop_uses_DROP_DEFAULT()
    {
        var r = Result(Db2Meta, new AttributeDefaultChanged(StatusCol, Customer, "'OLD'", ""));
        new Db2Emitter().Emit(r).Statements[0].Sql
            .Should().Be("ALTER TABLE \"CUSTOMER\" ALTER COLUMN \"status\" DROP DEFAULT;");
    }
}
